pipeline:
  build:
    when:
      event: push
    image: plugins/docker
    repo: registry.usw.co/cloud/node-problem-detector
    tags:
    - "${DRONE_COMMIT}"
    - "${DRONE_BRANCH}"

  build-tag:
    when:
      event: tag
      branch: master
    image: plugins/docker
    repo: registry.usw.co/cloud/node-problem-detector
    tags:
    - "${DRONE_TAG}"
