pipeline:
  build-commit:
    when:
      event: push
    image: plugins/docker
    repo: registry.usw.co/cloud/node-problem-detector
    tags:
    - "${DRONE_BRANCH}"
    - "${DRONE_COMMIT}"

  build-master:
    when:
      event: push
      branch: master
    image: plugins/docker
    repo: registry.usw.co/cloud/node-problem-detector
    tags:
    - master

  build-tag:
    when:
      event: tag
      branch: master
    image: plugins/docker
    repo: registry.usw.co/cloud/node-problem-detector
    tags:
    - "${DRONE_TAG}"
